configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/home-nguyenhoaibao-zbbs6d%2Fbookstore-2-bb50dbbe1137564ee4b549eb1efed1a45efc72657a498da377fe6f0babd032dd.yml
